### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by SchoeniosX** [A1y0sh4/The-Great-Unciv-Rework#57]
Do you have the time or desire to create such transitions and add them to your mod? Nature and surroundings should enhance maps. I would be very grateful to you.

![Screenshot_20240510-231151_Unciv](https://github.com/A1y0sh4/The-Great-Unciv-Rework/assets/148587231/fe567f08-e38f-44de-90d8-d784a6588459)
![Screenshot_20240510-232052_Unciv](https://github.com/A1y0sh4/The-Great-Unciv-Rework/assets/148587231/725ea107-2f1e-471d-961f-14656719a98f)

**Comment by A1y0sh4** [comment]
Yeah, I could do it in the future. From which mod do these images come from?

**Comment by SchoeniosX** [comment]
Hello A1y0sh4, 

The images come from the mod: Geneciv

**Comment by A1y0sh4** [comment]
Thank you very much. I'll give it a look and I'll see what I can do

**Comment by A1y0sh4** [comment]
Apparently I can't test the mod since its for an older version of the game

**Comment by SchoeniosX** [comment]
How exactly do you test the mod? Can I help you? And why can't they test the mod, is the version a problem?
