### ISSUE TITLE
Policy 

### ISSUE THREAD

**Issue by SchoeniosX** [A1y0sh4/The-Great-Unciv-Rework#62]
Have you made any changes to diplomatic policy? In my opinion it is no longer a question of deplomty in this branch, but of espionage after the change.

**Comment by A1y0sh4** [comment]
Yeah, I would like to make the Diplomacy tree something of a mix of diplomacy and espionage while making Internationalism more City-states related (in this way it matches for the end game the diplomatic victory aim). Anyway, Its all currently WIP and suggestion are more than welcome
