### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by fl0k1th3b0atbuild3r** [A1y0sh4/The-Great-Unciv-Rework#90]
im not a coder. plz help.
[uncivcrashreport.txt](https://github.com/user-attachments/files/16660501/uncivcrashreport.txt)

**Comment by fl0k1th3b0atbuild3r** [comment]
i deleted all other mods. started a new game. this happened.

**Comment by fl0k1th3b0atbuild3r** [comment]
[new crash.txt](https://github.com/user-attachments/files/16663899/new.crash.txt)

i figured that first issue was same as parthenon. so i started a new game didn't built parthenon this happened.

**Comment by fl0k1th3b0atbuild3r** [comment]
here is my save file
[Autosave-Sumeria-130.zip](https://github.com/user-attachments/files/16664061/Autosave-Sumeria-130.zip)

**Comment by A1y0sh4** [comment]
I didn't manage to reproduce the issue on my pc. I would suggest you to directly send these saves to Yarm, the creator of Unciv
